apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mysql-PodDisruptionBudget
  namespace: exam
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: mysql

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-PodDisruptionBudget
  namespace: exam
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: backend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-PodDisruptionBudget
  namespace: exam
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: frontend
